export const GET_EXPENSES = "GET_EXPENSES";
export const LOADING_EXPENSES = "LOADING_EXPENSES";
export const ADD_EXPENSE_GROUP = "ADD_EXPENSE_GROUP";
export const DELETE_EXPENSE_GROUP = "DELETE_EXPENSE_GROUP";
export const ADD_EXPENSE_CATEGORY = "ADD_EXPENSE_CATEGORY";
export const ADD_EXPENSE_ITEM = "ADD_EXPENSE_ITEM";

export const GET_INCOME = "GET_INCOME";
export const LOADING_INCOME = "LOADING_INCOME";
export const ADD_INCOME_GROUP = "ADD_INCOME_GROUP";
export const DELETE_INCOME_GROUP = "DELETE_INCOME_GROUP";
export const ADD_INCOME_CATEGORY = "ADD_INCOME_CATEGORY";
export const ADD_INCOME_ITEM = "ADD_INCOME_ITEM";
