export const GET_EXPENSES = "GET_EXPENSES";
export const LOADING_EXPENSES = "LOADING_EXPENSES";
export const ADD_EXPENSE_CARD = "ADD_EXPENSE_CARD";
export const DELETE_EXPENSE_CARD = "DELETE_EXPENSE_CARD";
export const ADD_EXPENSE_CATEGORY = "ADD_EXPENSE_CATEGORY";
export const ADD_EXPENSE_ITEM = "ADD_EXPENSE_ITEM";
