export const GET_EXPENSES = "GET_EXPENSES";
export const LOADING_EXPENSES = "LOADING_EXPENSES";
export const ADD_EXPENSE_GROUP = "ADD_EXPENSE_GROUP";
export const DELETE_EXPENSE_GROUP = "DELETE_EXPENSE_GROUP";
export const ADD_EXPENSE_CATEGORY = "ADD_EXPENSE_CATEGORY";
export const ADD_EXPENSE_ITEM = "ADD_EXPENSE_ITEM";

export const GET_INCOME = "GET_INCOME";
export const LOADING_INCOME = "LOADING_INCOME";
export const ADD_INCOME_GROUP = "ADD_INCOME_GROUP";
export const DELETE_INCOME_GROUP = "DELETE_INCOME_GROUP";
export const ADD_INCOME_CATEGORY = "ADD_INCOME_CATEGORY";
export const ADD_INCOME_ITEM = "ADD_INCOME_ITEM";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
